on:
  schedule:
  - cron: '34 3,4,5,6,9,12 * * *'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  fcast3:
    runs-on: ubuntu-latest
    outputs:
      out: ${{ steps.fcast.outputs.outputs }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Root CAs
      run: |
        yarn add --no-lockfile node_extra_ca_certs_mozilla_bundle

    - name: Fetch Forecast
      id: fcast
      uses: Wandalen/wretry.action@master
      env:
        NODE_EXTRA_CA_CERTS: node_modules/node_extra_ca_certs_mozilla_bundle/ca_bundle/ca_intermediate_root_bundle.pem
      with:
        action: dvuckovic/data-miner/.github/actions/fcast@main
        attempt_limit: 3

  deploy:
    if: success() && github.ref == 'refs/heads/main'
    needs: fcast3
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure Pages
      uses: actions/configure-pages@v2

    - name: Prepare Output Files
      env:
        JSON: ${{ fromJSON(needs.fcast3.outputs.out).json }}
        XML: ${{ fromJSON(needs.fcast3.outputs.out).xml }}
      run: |
        mkdir -p _site
        echo "$JSON" > ./_site/fcast3.json
        echo "$XML" > ./_site/fcast3.xml
        test -f ./_site/fcast3.json
        test -f ./_site/fcast3.xml

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v1

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
