on:
  schedule:
  - cron: '34 3,4,5,6,9,12 * * *'

  workflow_dispatch:

jobs:
  fcast3:
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.fcast.outputs.json }}
      xml: ${{ steps.fcast.outputs.xml }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Fetch Forecast
      id: fcast
      uses: ./.github/actions/fcast

  deploy:
    if: success() && github.ref == 'refs/heads/main'
    needs: fcast3
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: gh-pages

    - name: Prepare Output Files
      env:
        JSON: ${{ needs.fcast3.outputs.json }}
        XML: ${{ needs.fcast3.outputs.xml }}
      run: |
        rm -f CNAME
        echo "$JSON" > ./fcast3.json
        echo "$XML" > ./fcast3.xml
        test -f ./fcast3.json
        test -f ./fcast3.xml

    - name: Deploy to Github Pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        commit_message: Deployed to Github Pages.
        fqdn: data.dvuckovic.com
        build_dir: .
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Keepalive Workflow
      uses: gautamkrishnar/keepalive-workflow@1.0.7
      with:
        commit_message: Added an empty commit to keep scheduled GitHub workflows alive in this repository.
        committer_username: github-actions[bot]
        committer_email: 41898282+github-actions[bot]@users.noreply.github.com
